#!/bin/csh
#PBS -S /bin/csh
#PBS -N MSL-10s
#PBS -q normal
#PBS -l select=1:ncpus=28:mpiprocs=28:model=bro
#PBS -l walltime=8:00:00
#PBS -W group_list=s2061
#PBS -j oe
#
source /usr/local/lib/init/global.cshrc
module purge
module load mpi-hpe comp-intel
#
echo "I ran on:"
cat $PBS_NODEFILE
#
cd $PBS_O_WORKDIR
mpiexec -np 28 /nobackupp8/aborner/react-fixes/src-radiative-equi/spa_pleiades < in.MSL-10s > MSL-10s.out
